### ISSUE TITLE
2020-07-07 (Tue, Jul 7)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#10]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Reference(s)**

**Comment by guylepage3** [comment]
**sunday**
- [x] monthly calendar setup.
- [x] worked on sprint setup.
- [ ] organizing backups, hard drives and files
- [ ] start miami move checklist


**monday**
- [x] ~~

**today**
- [x] review.
- [x] finances.
- [x] work on sprint setup.
- [ ] organizing backups, hard drives and files.
- [ ] start miami move checklist.
