### ISSUE TITLE
2020-07-08 (Wed, Jul 8)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#11]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Reference(s)**

**Comment by guylepage3** [comment]
**yesterday**
- [x] review.
- [x] finances.
- [x] worked on sprint setup.
- [ ] organizing backups, hard drives and files.
- [ ] start miami move checklist.

**today**
- [x] review.
- [x] finances.
- [ ] finalize sprint setup.
- [ ] organizing backups, hard drives and files.
- [ ] 2019 taxes.
- [ ] work on miami move checklist.
