### ISSUE TITLE
2020-07-22 (Wed, Jul 22)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#13]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Reference(s)**

**Comment by guylepage3** [comment]
**yesterday**
- [x] finances.
- [x] worked on automating monthly budget P&L spreadsheet
- [x] worked on miami move.
- [x] started research on GPT-3 by OpenAI.

**today**
- [x] review.
- [x] more research on GPT-3 by OpenAI.
- [ ] work on automating monthly budget P&L spreadsheet
- [ ] work on miami move checklist.
- [ ] organizing backups, hard drives and files.
- [ ] 2019 taxes.
