### ISSUE TITLE
2020-08-03 (Mon, Aug 3)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#14]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Reference(s)**

**Comment by guylepage3** [comment]
**yesterday**
- [x] worked on miami move.
- [x] worked on 2019 taxes.

**today**
- [x] review.
- [ ] finances.
- [ ] sprint setup.
- [ ] work on automating monthly budget P&L spreadsheet
- [ ] work on miami move checklist.
- [ ] work on Q3 strategy.
- [ ] organizing backups, hard drives and files.
- [ ] work on 2019 taxes.
