### ISSUE TITLE
2020-03-25 (Wed, Mar 25)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#5]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Comment by guylepage3** [comment]
**monday**
- [x] worked on financial review (daily).
- [x] worked on covid-19 strategy.

**yesterday**
- [x] worked on financial review (daily).
- [x] worked on covid-19 strategy.
- [x] admin.

**today**
- [x] setup `universe-standup` repository readme.
- [x] admin.
- [ ] work on financial review (daily).
- [ ] work on covid-19 strategy.
