### ISSUE TITLE
2020-04-01 (Wed, Apr 1)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#7]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Comment by guylepage3** [comment]
**friday**
- [x] work on financial review (daily).
- [x] work on covid-19 strategy.

**saturday**
- [x] work on financial review (daily).
- [x] work on covid-19 strategy.

**sunday**
- [x] work on financial review (daily).
- [x] work on covid-19 strategy.

**monday**
- [x] admin.
- [x] work on financial review (daily).
- [x] work on covid-19 strategy.

**yesterday**
- [x] work on financial review (daily).
- [x] work on covid-19 strategy.

**today**
- [x] work on financial review (daily).
- [x] admin
- [x] monthly financials.
- [x] work on covid-19 strategy.
