### ISSUE TITLE
2020-04-07 (Tue, Apr 7)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#8]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Comment by guylepage3** [comment]
**wednesday**
- [x] worked on financial review (daily).
- [x] admin
- [x] monthly financials.
- [x] worked on covid-19 strategy.

**thursday**
- [x] worked on financial review (daily).
- [x] admin
- [x] monthly financials.

**friday**
- [x] worked on financial review (daily).
- [x] admin

**saturday**
- [x] worked on financial review (daily).
- [x] admin

**yesterday**
- [x] worked on financial review (daily).
- [x] admin

**today**
- [ ] work on financial review (daily).
- [ ] admin
- [ ] monthly financials.
