### ISSUE TITLE
2020-07-05 (Sun, Jul 5)

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-standup#9]
**Description**
Daily Standup (SCRUM) for team & community to post what they are working on. 

Intended to prevent overlap of duties and assist in reaching Sprint goals.

**Tasks**
1. Post previous day(s) tasks worked on.
1. Post tasks to be worked on today.

**Reference(s)**

**Comment by guylepage3** [comment]
**today**
- [x] monthly calendar setup.
- [x] sprint setup.
- [ ] organizing backups, hard drives and files
- [ ] start miami move checklist
